# Generated by Django 5.2.3 on 2025-07-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_userinformation_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
