# Generated by Django 5.2.3 on 2025-08-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_userinformation_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
